// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://baziigjzvtjurrqypkca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhemlpZ2p6dnRqdXJycXlwa2NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NzU5NDcsImV4cCI6MjA2NTE1MTk0N30.u6Rva9oMQmy0Qca2cnNqbyncp0wgliERTAUx7Vm1bHk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);